# Generated by Django 5.2.13 on 2026-05-02 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='familydata',
            table='family_data',
        ),
    ]
